routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/parking_zone', 'HomeController@ParkingZone');
Route::get('/pricelist/{id}', 'HomeController@pricelist');
Route::get('/periodprice/{id}', 'HomeController@periodprice');
Route::get('/vehicleperiod/{id}/{parking_name}', 'BookingController@vehicleperiod');
Route::get('/vehicleprice/{id}', 'BookingController@vehicleprice');

Route::resource('/rentuser-parkingzone', 'RentUserController');

Route::resource('/booking', 'BookingController')->middleware('auth');
Route::resource('/uservehicle', 'UserVehicleController');
Route::post('/bookingvehicle', 'BookingController@booking');
Route::get('/confiramation/{id}', 'BookingController@Confiramation');

Route::get('/booking-history', 'ProfileController@bookinghistory');

Auth::routes();

Route::get('/admin', 'AdminController@index');
Route::get('/myprofile', 'ProfileController@myprofile');

Route::get('/admin/login', 'AdminController@adminLogin');

Route::prefix('admin')->group(function () {
    Route::middleware('auth')->group(function () {

        Route::group(['middleware' => ['role:Supper Admin']], function () {
    
            Route::resource('/role', 'RoleController');

            Route::resource('/permission', 'PermissionController');

            Route::resource('/role-permission', 'RolePermissionController');

            Route::resource('/user-access', 'UserAccessController');

        });

        Route::group(['middleware' => ['role:Supper Admin|Admin','permission:Vehicle|ParkingPrice|ZoneLocation|PaymentMethod|AppSettings']], function () {
            
            Route::resource('/vehicle', 'VehicleController');

            Route::resource('/payment_method', 'PaymentMethodController');

            Route::resource('/appsettings', 'AppSettingsController');

            Route::resource('/parkingprice', 'ParkingPriceController');

            Route::resource('/locationzone', 'LocationZoneController');

        });

        Route::resource('/profile', 'ProfileController');

        Route::get('pass', 'ProfileController@checkpass')->name('pass');

        Route::resource('/parkingzone', 'ParkingZoneController');

        Route::get('/parkingzone/vehicle_data/{id}', 'ParkingZoneController@vehicle_data');

        Route::get('/parkingzone/package_data/{id}', 'ParkingZoneController@package_data');
        //Booking List
        Route::get('/booking_list', 'BookingController@booking_list');
        //Booking Release
        Route::get('/booking_release/{id}', 'BookingController@booking_release');
        //Active Booking
        Route::get('/active-booking', 'BookingController@activebooking');
        //Today Booking
        Route::get('/today-booking', 'BookingController@todaybooking');

    });
});

Route::get('/verifyemail/{token}', 'HomeController@verifyemail')->name('verifyemail');

Route::resource('/customer_register', 'CustomerController');

Route::post("/customer_login", "CustomerController@login");

Route::get("/rent_register", "CustomerController@rent_register");
Route::get("/rent_register", "CustomerController@rent_register");
Route::get("/about", "aboutController@index")->name('about');

resources/views/frontend/about.blade.php
@extends('frontend.layouts.frontend_main')
@section('title')About | Park AnyWhere @endsection
@section('css')
@endsection
@section('content')
<section class="about_section">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="about_img">
                    <img src="frontend_assets/images/road2.jpg" alt="About Us Image ParkAnyWhere">
                </div>
            </div>
            <div class="col-lg-6 col-lg-offset-1">
                <div class="about_text">
                    <h2>About Us</h2>
                    <p class="about_text">Park AnyWhere is the best way to find parking online. We can provide parking information for millions of vehicle user in Bangladesh.
                        
                    Our model is simple. We help you park safely (Monthly & Hourly) in our nearest parking hubs & contracted residence parking places where we maintain security, parking automations & 24/7 cc tv surveillance.
                
                    Our IoT-based smart parking system provides a unique solution to the roadside parking problem in the country. 30% of the traffic problems are created due to roadside parking & our mission is to solve this problem as well as traffic congestion in the process. In a way everyone associated with ParkAnyWhere is working for a better Bangladesh.</p>
                    <a href="javascript:void()">Learn More</a>
             </div>
            </div>
        </div> 
    </div>
</section>
@endsection

resources/views/frontend/parking_zone.blade.php
<div class="col-sm-12 mb-2">
    <div class="profiles-details">
        <table class="table table-condensed table-bordered table-hover">
            <thead>
            <tr class="bg-indigo">
                <th><i class="glyphicon glyphicon-flag"></i> Parking Lots</th>
                <th class="hidden-xs">Total</th>
                <th class="hidden-xs">Booking</th>
                <th>Available</th>
                <th><i class="material-icons">Action</i></th>
            </tr>
            </thead>
            <tbody>
            @foreach($parkingzone as $parking_data)
                <tr>
                    <th data-geolocation="{{$parking_data->parking_zone_id}},{{$parking_data->latitude}},{{$parking_data->longitude}}"
                        data-title="{{$parking_data->parking_name}}" class="showMapByGeoLocation"
                        style="cursor: pointer; word-wrap: break-word;">{{$parking_data->parking_name}}</th>
                    <td class="hidden-xs"><strong class="label label-info">{{$parking_data->parking_limit}}</strong>
                    </td>
                    <td class="hidden-xs"><strong
                            class="label label-warning">@php print_r($parking_data->ParkingSpace->where('booking_status',0)->count()) @endphp</strong>
                    </td>
                    <td><strong
                            class="label label-success"> @php print_r($parking_data->ParkingSpace->where('booking_status',1)->count()) @endphp   </strong>
                    </td>

                    <td>
                        <button class="btn btn-xs btn-primary" data-id="{{$parking_data->parking_zone_id}}"
                                data-title="{{$parking_data->parking_name}}" data-toggle="modal"
                                data-target="#priceModal"><i class="fas fa-dollar-sign"></i></button>
                        <button class="btn btn-xs btn-info hidden-xs showMapByGeoLocation"
                                data-geolocation="{{$parking_data->parking_zone_id}},{{$parking_data->latitude}},{{$parking_data->longitude}}">
                            <i class="fas fa-map-marker-alt"></i></button>
                        @guest
                            <button class="btn btn-sm btn-success" disabled>Booking Now</button>
                        @endguest
                        @auth
                            <a href="{{route('booking.show',$parking_data->parking_zone_id)}}"
                               class="btn btn-sm btn-success">Booking Now</a>
                        @endauth
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>