routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/parking_zone', 'HomeController@ParkingZone');
Route::get('/pricelist/{id}', 'HomeController@pricelist');
Route::get('/periodprice/{id}', 'HomeController@periodprice');
Route::get('/vehicleperiod/{id}/{parking_name}', 'BookingController@vehicleperiod');
Route::get('/vehicleprice/{id}', 'BookingController@vehicleprice');

Route::resource('/rentuser-parkingzone', 'RentUserController');

Route::resource('/booking', 'BookingController')->middleware('auth');
Route::resource('/uservehicle', 'UserVehicleController');
Route::post('/bookingvehicle', 'BookingController@booking');
Route::get('/confiramation/{id}', 'BookingController@Confiramation');

Route::get('/booking-history', 'ProfileController@bookinghistory');

Auth::routes();

Route::get('/admin', 'AdminController@index');
Route::get('/myprofile', 'ProfileController@myprofile');

Route::get('/admin/login', 'AdminController@adminLogin');

Route::prefix('admin')->group(function () {
    Route::middleware('auth')->group(function () {

        Route::group(['middleware' => ['role:Supper Admin']], function () {
    
            Route::resource('/role', 'RoleController');

            Route::resource('/permission', 'PermissionController');

            Route::resource('/role-permission', 'RolePermissionController');

            Route::resource('/user-access', 'UserAccessController');

        });

        Route::group(['middleware' => ['role:Supper Admin|Admin','permission:Vehicle|ParkingPrice|ZoneLocation|PaymentMethod|AppSettings']], function () {
            
            Route::resource('/vehicle', 'VehicleController');

            Route::resource('/payment_method', 'PaymentMethodController');

            Route::resource('/appsettings', 'AppSettingsController');

            Route::resource('/parkingprice', 'ParkingPriceController');

            Route::resource('/locationzone', 'LocationZoneController');

        });

        Route::resource('/profile', 'ProfileController');

        Route::get('pass', 'ProfileController@checkpass')->name('pass');

        Route::resource('/parkingzone', 'ParkingZoneController');

        Route::get('/parkingzone/vehicle_data/{id}', 'ParkingZoneController@vehicle_data');

        Route::get('/parkingzone/package_data/{id}', 'ParkingZoneController@package_data');
        //Booking List
        Route::get('/booking_list', 'BookingController@booking_list');
        //Booking Release
        Route::get('/booking_release/{id}', 'BookingController@booking_release');
        //Active Booking
        Route::get('/active-booking', 'BookingController@activebooking');
        //Today Booking
        Route::get('/today-booking', 'BookingController@todaybooking');

    });
});

Route::get('/verifyemail/{token}', 'HomeController@verifyemail')->name('verifyemail');

Route::resource('/customer_register', 'CustomerController');

Route::post("/customer_login", "CustomerController@login");

Route::get("/rent_register", "CustomerController@rent_register");
Route::get("/rent_register", "CustomerController@rent_register");
Route::get("/about", "aboutController@index")->name('about');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Permission\Traits\HasRoles;
class User extends Authenticatable
{
    use Notifiable,  SoftDeletes, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $primaryKey='id';
    protected $fillable = [
        'name', 'email', 'password', 'gender', 'number', 'profile_image', 'email_verified', 'email_verified_at', 'email_verification_token','created_by','updated_by'
    ];

    public function loginValidation()
    {
        return [
            "email" => "required|email",
            "password" => "required",
        ];
    }


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/RentUserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\LocationZone;
use App\ParkingZone;
use Auth;

class RentUserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user_id = Auth::user()->id;
        $parkingzone_data = ParkingZone::where('created_by', $user_id)->orderBy('parking_zone_id', 'desc')->get();
        return view('frontend.Users.RentUser.parking_list', ['parkingzone_data' => $parkingzone_data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $location_zone = LocationZone::Active()->get();
        return view('frontend.Users.RentUser.rentuser_parking_zone', ['location_zone' => $location_zone]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/frontend/Users/RentUser/parking_list.blade.php
@extends('frontend.layouts.frontend_main')
@section('title') Parking List | Park AnyWhere @endsection
@section('css')

@endsection
@section('content')

    <div class="main-content">
        <div class="data-table-area">
            <div class="container-fluid">


                <div class="row">
                    <div class="col-12 box-margin">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title mb-2">Parking Zone List</h4>
                                <a class="card-title mb-2 pull-right" href="/rentuser-parkingzone/create">Add New
                                    Parking Zone</a>
                                <table id="basic-datatable" class="table table-striped dt-responsive nowrap w-100">
                                    <thead>
                                    <tr>

                                        <th>Sl</th>
                                        <th>Parking Name</th>
                                        <th>Latitude</th>
                                        <th>Longitude</th>
                                        <th>Limit</th>
                                        <th>Status</th>
                                        {{-- <th class="text-center">Action</th> --}}
                                    </tr>
                                    </thead>

                                    <tbody>
                                    @foreach($parkingzone_data as $key => $value)
                                        <tr>
                                            <td>{{$key+1}}</td>
                                            <td>{{$value->parking_name}}</td>
                                            <td>{{$value->latitude}}</td>
                                            <td>{{$value->longitude}}</td>
                                            <td>{{$value->parking_limit}}</td>
                                            <td>
                                                @if($value->parking_status==1)
                                                    <span class="text-success">Active</span>
                                                @else
                                                    <span class="text-danger">Inactive</span>
                                                @endif
                                            </td>
                                            {{--                                             <td class="text-center">
                                                                                            @if ($value->parking_status == 1)
                                                                                                <button type="submit"
                                                                                                        class="btn btn-rounded btn-outline-success mb-2 mr-2"
                                                                                                        id="parking_status" data="{{$value->parking_zone_id}}"><i
                                                                                                        class="fa fa-refresh" aria-hidden="true"></i></button>
                                                                                            @else
                                                                                                <button type="submit"
                                                                                                        class="btn btn-rounded btn-outline-danger mb-2 mr-2"
                                                                                                        id="parking_status" data="{{$value->parking_zone_id}}"><i
                                                                                                        class="fa fa-refresh" aria-hidden="true"></i></button>
                                                                                            @endif
                                                                                            <a href="{{route('parkingzone.edit',$value->parking_zone_id)}}"
                                                                                               class="btn btn-rounded btn-outline-info mb-2 mr-2">Edit</a>
                                                                                            <button type="submit"
                                                                                                    class="btn btn-rounded btn-outline-danger mb-2 mr-2 delete"
                                                                                                    data="{{ $value->parking_zone_id }}">Delete
                                                                                            </button>

                                                                                        </td> --}}
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>


                            </div> <!-- end card body-->
                        </div> <!-- end card -->
                    </div><!-- end col-->
                </div>
                <!-- end row-->


            </div>
        </div>


    </div>

@endsection

@section('script')



@endsection

resources/views/frontend/Users/RentUser/rentuser_parking_zone.blade.php
@extends('frontend.layouts.frontend_main')
@section('title') Add Parking Zone | Park AnyWhere @endsection
@section('css')

@endsection
@section('content')

    <div class="main-content">

        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-flex align-items-center justify-content-between">
                        <h4 class="mb-0 font-18">Add Parking Zone</h4>

                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Home</a></li>
                                <li class="breadcrumb-item active">Add Parking Zone</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Form row -->
            <div class="row">
                <div class="col-xl-6 box-margin height-card">
                    <div class="card card-body">
                        <h4 class="card-title">New Parking Zone</h4>
                        <div class="row">
                            <div class="col-sm-12 col-xs-12">
                                <form id="ParkingZone" action="{{route('parkingzone.store')}}" method="post"
                                      enctype="multipart/form-data">
                                    @csrf
                                    <label for="exampleInputEmail111">Parking Zone Name</label>
                                    <div class="form-group">

                                        <input type="text" class="form-control" name="parking_name" id="parking_name"
                                               placeholder="Parking Zone Name">
                                    </div>
                                    <span class="help-block" id="parking_name_error" style="color:red;"></span>
                                    <label for="exampleInputEmail111">Parking Zone Location</label>
                                    <div class="form-group">

                                        <select class="form-control" name="location_zone_name" id="location_zone_name">
                                            <option value="" selected hidden>Select Zone Location</option>
                                            @foreach($location_zone as $location_value)
                                                <option
                                                    value="{{$location_value->location_zone_id}}">{{$location_value->location_zone_name}}</option>
                                            @endforeach
                                        </select>

                                    </div>
                                    <span class="help-block" id="location_zone_name_error"
                                          style="color:red;"></span>
                                    <div class="row">

                                        <div class="col-md-6">
                                            <label>Latitude *</label>
                                            <div class="form-group">
                                                <input readonly type="text" class="form-control" name="latitude"
                                                       id="latitude"
                                                       placeholder="Latitude">
                                            </div>
                                            <span class="help-block" id="vehicle_time_error" style="color:red;"></span>

                                        </div>


                                        <div class="col-md-6">
                                            <label>Longitude *</label>
                                            <div class="form-group">
                                                <div class="input-group">
                                                    <input readonly id="longitude" name="longitude" type="text"
                                                           class="form-control"
                                                           placeholder="Longitude"
                                                           aria-label="Amount (to the nearest dollar)">
                                                    <div class="input-group-append">

                                                    </div>
                                                    <button type="button" onclick="placeMarker()"
                                                            class="btn btn-primary">
                                                        <i class="fa fa-hand-pointer-o"></i>
                                                    </button>
                                                </div>
                                            </div>
                                            <span class="help-block" id="Longitude_error" style="color:red;"></span>

                                        </div>

                                    </div>
                                    <label for="exampleInputEmail111">Parking Limit</label>
                                    <div class="form-group">
                                        <input type="number" min="1" class="form-control" name="parking_limit"
                                               id="parking_limit" placeholder="Parking Limit">

                                    </div>
                                    <span class="help-block" id="parking_limit_error" style="color:red;"></span>
                                    <label for="space">Space *
                                        <small class="text-success">(Click to generate space)</small>
                                        <button type="button" id="autoGenerateSerial"
                                                class="btn btn-xs bg-cyan  waves-effect">
                                            <i class="fa fa-refresh"></i>
                                        </button>

                                    </label>
                                    <div class="form-group">
                                        <input id="tags" name="parking_space" class="space" value=""/>
                                    </div>
                                    <span class="help-block" id="parking_space_error" style="color:red;"></span>
                                    <label for="exampleInputEmail111">Address</label>
                                    <div class="form-group">
                                        <textarea class="form-control" id="parking_address" name="parking_address"
                                                  placeholder="Type Parking Address"></textarea>

                                    </div>
                                    <span class="help-block" id="parking_address_error" style="color:red;"></span>
                                    <label for="exampleInputEmail111">Note</label>
                                    <div class="form-group">
                                        <textarea class="form-control" id="parking_note" name="parking_note"
                                                  placeholder="Type Package Note"></textarea>
                                    </div>
                                    {{--                                     <div class="form-group">
                                                                            <label for="inputState" class="col-form-label">Status</label>
                                                                            <select id="parking_status" name="parking_status" class="form-control">
                                                                                <option selected disabled hidden>Select</option>
                                                                                <option value="1">Active</option>
                                                                                <option value="0">Inactive</option>
                                                                            </select>
                                                                            <span class="help-block" id="parking_status_error" style="color:red;"></span>
                                                                        </div> --}}
                                    <button type="submit" style="background: green;padding: 7px 10px;margin-top: -1px;"
                                            class="submit btn btn-primary">Submit
                                    </button>
                                    <button type="reset" class="btn btn-danger">Reset</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-6 box-margin height-card">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Google Map</h4>
                            <h4 id="error" class="text-danger">Location tracked automatically.</h4>

                            <div id="map" style="width:100%;height:500px"></div>


                        </div> <!-- end card-body -->
                    </div> <!-- end card-->
                </div> <!-- end col -->


            </div>

            @endsection

            @section('js')

                <script async defer
                        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDDXkzEIj9sB3J_ohqT0woVWqAJQiyRmAE&maptype=roadmap&libraries=places&callback=initMap"></script>
                <script type="text/javascript" src="{{asset('ajax/parkingzone.js')}}"></script>

@endsection